=== 2848133264/sencond/mavenweb/src/main/resources/stu.dtd
<!ELEMENT stus (stu+)> 
<!-- 可以 + 号，可以 *（可以写可以不写） -->
<!ELEMENT stu (id*,name,age?,sex)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ATTLIST stu id CDATA #IMPLIED>
<!-- 可以给这个stu 添加一个id的属性  -->

<!ELEMENT score (forms*)>
<!ELEMENT forms (idd,subject,grades)>
<!ELEMENT idd (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT grades (#PCDATA)>

=== 2848133264/sencond/mavenweb/src/main/resources/stus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stus PUBLIC "//UNKNOWN" "stu.dtd">
<!-- 生成一个dtd文件 ,再去引用就行 -->
<!--  初始化数据。-->
<stus>
	<stu id="1000">
		<id>1000</id>
		<name>张三</name>
		<age>18</age>
		<sex>男</sex>
	</stu>
	<stu id="1002">
		<id>1002</id>
		<name>李四</name>
		<age>18</age>
		<sex>男</sex>
	</stu>
</stus>
